VisualResume::VisualResume(
  titles.left = c("Gabriel Cabrera", "Finanzas, Programación, R", "*Creado con corazón, tiempo, cafe... y R*"),
  titles.right = c("https://gcabrerag.rbind.io/", "gcabrerag@fen.uchile.cl", "CV completo: https://gcabrerag.rbind.io/ "),
  titles.right.cex = c(2, 2, 1),
  titles.left.cex = c(4, 2, 1),
  timeline.labels = c("Educación", "Teaching Assistent"),
  timeline = data.frame(title = c("Universidad de Chile", "Universidad de Chile", "Universidad de Chile", "Universidad de Chile", "Universidad de Chile", "Universidad de Chile", "Universidad de Chile",
                                  "Universidad de Chile", "Universidad Diego Portales", "Universidad Diego Portales"),
                        sub = c("BA. Economics", "MSc. Finance (c)", "Introducción a la tecnología", "Econometría Aplicada", "Finanzas I" , "Tópicos en Economía y Negocios utilizando R", 
                                "Entorno Económico para los negocios", "Econometría Avanzada", "R para Economía y Negocios", "Econometría I"),
                        start = c(2012, 2017, 2015, 2017, 2018, 2018, 2018.5, 2018.5, 2018.5, 2018.5),
                        end = c(2017, 2019, 2017, 2018, 2019, 2019, 2019, 2019, 2019, 2019),
                        side = c(1, 1, 0, 0, 0, 0, 0, 0, 1, 1)),
  milestones = data.frame(title = c("BA", "MSc"),
                          sub = c("Economics", "Finance"),
                          year = c(0, 0)),
  events = data.frame(year = c(2017, 2018),
                      title = c("Licenciatura Ciencia de la Economía, Universidad de Chile",
                                "Ingeniero Comercial, mención Economía, Universidad de Chile")),
  interests = list("programming" = c(rep("R", 10), rep("Python", 1), rep("JavaScript", 2), "MatLab"),
                   "statistics" = c(rep("Decision Trees", 10), rep("Bayesian", 5), rep("Regression", 3)),
                   "leadership" = c(rep("Motivation", 10), rep("Decision Making", 5), rep("Manipulation", 30))),
  year.steps = 1
)
